name: Build and Deploy to S3

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: read

env:
  # App-specific: Angular static output lives in the "browser" dir when outputMode=static
  BUILD_DIR: dist/fulghum.digital/browser

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync "$BUILD_DIR" "s3://${{ vars.S3_BUCKET }}" \
            --delete \
            --only-show-errors

      - name: (Optional) Invalidate CloudFront
        if: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"

